{
    "page": 1,
    "total_results": 6,
    "total_pages": 1,
    "results": [{
        "popularity": 8.873,
        "id": 274,
        "video": false,
        "vote_count": 10963,
        "vote_average": 8.3,
        "title": "The Silence of the Lambs",
        "release_date": "1991-02-01",
        "original_language": "en",
        "original_title": "The Silence of the Lambs",
        "genre_ids": [80, 18, 53, 27],
        "backdrop_path": "\/pI9B4wppGflpsOD2T6rxgC5Clmz.jpg",
        "adult": false,
        "overview": "Clarice Starling is a top student at the FBI's training academy. Jack Crawford wants Clarice to interview Dr. Hannibal Lecter, a brilliant psychiatrist who is also a violent psychopath, serving life behind bars for various acts of murder and cannibalism. Crawford believes that Lecter may have insight into a case and that Starling, as an attractive young woman, may be just the bait to draw him out.",
        "poster_path": "\/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg"
    }, {
        "popularity": 6.119,
        "id": 401439,
        "video": false,
        "vote_count": 3,
        "vote_average": 8,
        "title": "Inside the Labyrinth: The Making of 'The Silence of the Lambs'",
        "release_date": "2001-01-01",
        "original_language": "en",
        "original_title": "Inside the Labyrinth: The Making of 'The Silence of the Lambs'",
        "genre_ids": [99],
        "backdrop_path": null,
        "adult": false,
        "overview": "A behind-the-scenes look at the making of this Oscar winning thriller, prepared for its tenth anniversary. Includes interviews with star Anthony Hopkins, as well as other members of the cast and crew, giving their views on the experience of creating this masterpiece of terror and suspense.",
        "poster_path": "\/2NMhqlNgzHnWgfJ15Yr2XFiDcYr.jpg"
    }, {
        "popularity": 2.405,
        "vote_count": 1,
        "video": false,
        "poster_path": "\/pnBKp4tspdhNbKSingcBBzZGF8s.jpg",
        "id": 384189,
        "adult": false,
        "backdrop_path": null,
        "original_language": "en",
        "original_title": "Inside Story: The Silence of the Lambs",
        "genre_ids": [99],
        "title": "Inside Story: The Silence of the Lambs",
        "vote_average": 7,
        "overview": "When it was released in 1991, director Jonathan Demme's adaptation of Thomas Harris' Silence of the Lambs, starring Jodie Foster and featuring an unforgettable performance by Anthony Hopkins, changed the rules of how horror could be presented in mainstream film; the Oscar-winning classic's reverberations continue today, while the Hannibal Lecter money train keeps on rolling. This 90-minute documentary on the inside story of the Silence of the Lambs shows just how all the right elements came together to create a modern classic.",
        "release_date": "2010-09-08"
    }, {
        "popularity": 1.428,
        "id": 692291,
        "video": false,
        "vote_count": 0,
        "vote_average": 0,
        "title": "The Making of 'The Silence of the Lambs'",
        "release_date": "1991-08-20",
        "original_language": "en",
        "original_title": "The Making of 'The Silence of the Lambs'",
        "genre_ids": [99, 53, 27],
        "backdrop_path": null,
        "adult": false,
        "overview": "This brief throwback piece focused on interview snippets from Hopkins, Demme, Glenn, Foster, FBI agent John Douglas and another unnamed FBI agent.",
        "poster_path": "\/ldxA9OxJyM7XtzXlQmT5FbZ0A58.jpg"
    }, {
        "popularity": 1.567,
        "id": 526065,
        "video": false,
        "vote_count": 0,
        "vote_average": 0,
        "title": "Page to Screen: The Silence of the Lambs",
        "release_date": "2002-10-28",
        "original_language": "en",
        "original_title": "Page to Screen: The Silence of the Lambs",
        "genre_ids": [99],
        "backdrop_path": null,
        "adult": false,
        "overview": "Documentary about the adaptation of the 1988 novel by Thomas Harris into the 1991 film directed by Jonathan Demme. Originally presented in two parts on Bravo Television.",
        "poster_path": "\/d1Ym3OtrPE225KpNJYuC74KPAWx.jpg"
    }, {
        "popularity": 6.821,
        "vote_count": 3024,
        "video": false,
        "poster_path": "\/v5wAZwRqpGWmyAaaJ8BBHYuNXnj.jpg",
        "id": 9740,
        "adult": false,
        "backdrop_path": "\/leoX6riSecG8zkfimFUQlfzTuGW.jpg",
        "original_language": "en",
        "original_title": "Hannibal",
        "genre_ids": [80, 18, 27, 53],
        "title": "Hannibal",
        "vote_average": 6.7,
        "overview": "After having successfully eluded the authorities for years, Hannibal peacefully lives in Italy in disguise as an art scholar. Trouble strikes again when he's discovered leaving a deserving few dead in the process. He returns to America to make contact with now disgraced Agent Clarice Starling, who is suffering the wrath of a malicious FBI rival as well as the media.",
        "release_date": "2001-02-08"
    }]
}