export const UPDATE_MOVIES_TO_DISPLAY = "UPDATE_MOVIES_TO_DISPLAY";
export const ADD_TO_REMOVED_MOVIES = "ADD_TO_REMOVED_MOVIES";
export const UPDATE_REMOVED_MOVIES = "UPDATE_REMOVED_MOVIES";
export const ADD_TO_SAVED_MOVIES = "ADD_TO_SAVED_MOVIES";
export const UPDATE_SAVED_MOVIES = "UPDATE_SAVED_MOVIES";
