export const ADD_TO_MOVIES = "ADD_TO_MOVIES";
export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const ADD_TO_DISLIKED_MOVIES = "ADD_TO_DISLIKED_MOVIES";
export const UPDATE_DISLIKED_MOVIES = "UPDATE_DISLIKED_MOVIES";
export const ADD_TO_LIKED_MOVIES = "ADD_TO_LIKED_MOVIES";
export const UPDATE_LIKED_MOVIES = "UPDATE_LIKED_MOVIES";
