export const ADD_TO_MOVIES = "ADD_TO_MOVIES";
export const UPDATE_MOVIES = "UPDATE_MOVIES";
export const ADD_TO_DISLIKED_MOVIES = "ADD_TO_DISLIKED_MOVIES";
export const ADD_TO_LIKED_MOVIES = "ADD_TO_LIKED_MOVIES";
export const UPDATE_MOVIE_PREFERENCES = "UPDATE_MOVIE_PREFERENCES";
